# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionalStatement',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_category_id', models.IntegerField()),
                ('statement', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'directional_statement',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_category_short_name', models.CharField(max_length=3)),
                ('food_category_long_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'food_category',
            },
        ),
        migrations.CreateModel(
            name='FoodDetailCategory',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_category_id', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'food_detail_category',
            },
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_detail_category_id', models.IntegerField()),
                ('food_category_id', models.IntegerField()),
                ('serving_size', models.CharField(max_length=100)),
                ('food_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'foodentry',
            },
        ),
        migrations.CreateModel(
            name='Serving',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_category_id', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('age_lower', models.IntegerField()),
                ('age_upper', models.IntegerField()),
                ('serving_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'serving',
            },
        ),
    ]
