# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20171022_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionalstatement',
            name='food_category_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fooddetailcategory',
            name='food_category_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='food_category_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='food_detail_category_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serving',
            name='food_category_id',
            field=models.IntegerField(),
        ),
    ]
