# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20171022_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionalstatement',
            name='food_category_id',
            field=models.ForeignKey(db_column='food_category_id', on_delete=django.db.models.deletion.CASCADE, to='challenge.FoodCategory'),
        ),
        migrations.AlterField(
            model_name='fooddetailcategory',
            name='food_category_id',
            field=models.ForeignKey(db_column='food_category_id', on_delete=django.db.models.deletion.CASCADE, to='challenge.FoodCategory'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='food_category_id',
            field=models.ForeignKey(db_column='food_category_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='challenge.FoodCategory'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='food_detail_category_id',
            field=models.ForeignKey(db_column='food_detail_category_id', on_delete=django.db.models.deletion.CASCADE, to='challenge.FoodDetailCategory'),
        ),
        migrations.AlterField(
            model_name='serving',
            name='food_category_id',
            field=models.ForeignKey(db_column='food_category_id', on_delete=django.db.models.deletion.CASCADE, to='challenge.FoodCategory'),
        ),
    ]
